
let erp90SelectedProduct=-1,erp90SelectedCustomer=null,erp90SelectedSupplier=null;
function e90(v){return escapeHtml(String(v??''))}
function erp90InitFilters(){
 const pb=document.getElementById('p90brand'),pc=document.getElementById('p90cat');if(!pb||!pc)return;
 const b=[...new Set((state.products||[]).map(x=>x.brand).filter(Boolean))].sort(); const c=[...new Set((state.products||[]).map(x=>x.category).filter(Boolean))].sort();
 pb.innerHTML='<option value="">全部品牌</option>'+b.map(x=>`<option>${e90(x)}</option>`).join('');pc.innerHTML='<option value="">全部分類</option>'+c.map(x=>`<option>${e90(x)}</option>`).join('');
}
function erp90RenderProducts(){
 erp90InitFilters();const q=norm(document.getElementById('p90q')?.value||'').toLowerCase(),b=p90brand.value,c=p90cat.value;
 const rows=(state.products||[]).map((p,i)=>({p,i})).filter(({p})=>(!q||norm([p.id,p.description,p.storeCode,p.barcode,p.brand,p.category,p.channel].join(' ')).toLowerCase().includes(q))&&(!b||p.brand===b)&&(!c||p.category===c));
 p90count.textContent=`共找到 ${rows.length} 筆商品資料`;
 p90list.innerHTML=rows.length?`<table class="erp90-table"><thead><tr><th>型號</th><th>品名</th><th>品牌</th><th>庫存</th><th>售價</th></tr></thead><tbody>${rows.slice(0,500).map(({p,i})=>`<tr class="${i===erp90SelectedProduct?'selected':''}" onclick="erp90EditProduct(${i})" ondblclick="erp90EditProduct(${i})"><td><b>${e90(p.id)}</b><div class="muted">${e90(p.storeCode||p.barcode||'')}</div></td><td>${e90(p.description||'')}</td><td>${e90(p.brand||'')}</td><td>${e90(p.stock||0)}</td><td>$${money(Number(p.suggested||calc(p).end||0))}</td></tr>`).join('')}</tbody></table>`:'<div class="erp90-empty">查無商品資料</div>';
}
function erp90EditProduct(i){const p=state.products[i];if(!p)return;erp90SelectedProduct=i;p90idx.value=i;p90title.textContent='修改商品：'+(p.id||'');p90id.value=p.id||'';p90store.value=p.storeCode||'';p90desc.value=p.description||'';p90brandEdit.value=p.brand||'';p90catEdit.value=p.category||'';p90channel.value=p.channel||'';p90barcode.value=p.barcode||'';p90stock.value=p.stock||0;p90suggested.value=p.suggested||0;p90dealer.value=p.dealer||0;p90direct.value=p.directPrice??p.direct??0;erp90RenderProducts()}
function erp90NewProduct(){erp90SelectedProduct=-1;p90idx.value='';p90title.textContent='新增商品';['p90id','p90store','p90desc','p90brandEdit','p90catEdit','p90channel','p90barcode','p90stock','p90suggested','p90dealer','p90direct'].forEach(id=>document.getElementById(id).value='');p90stock.value=0;p90suggested.value=0;p90dealer.value=0;p90direct.value=0}
function erp90SaveProduct(){const id=p90id.value.trim();if(!id)return toast('請輸入商品型號／品號');let p=erp90SelectedProduct>=0?state.products[erp90SelectedProduct]:null;if(!p){p={customProduct:true};state.products.unshift(p);erp90SelectedProduct=0}Object.assign(p,{id,storeCode:p90store.value.trim(),description:p90desc.value.trim(),brand:p90brandEdit.value.trim(),category:p90catEdit.value.trim(),channel:p90channel.value.trim()||'自建商品',barcode:p90barcode.value.trim(),stock:Number(p90stock.value||0),suggested:Number(p90suggested.value||0),dealer:Number(p90dealer.value||0),directPrice:Number(p90direct.value||0)});persist('ERP10.0修改商品',true);renderSelects();erp90InitFilters();erp90RenderProducts();toast('商品資料已儲存')}
function erp90DeleteProduct(){if(erp90SelectedProduct<0)return toast('請先選擇商品');if(!confirm('確定刪除這筆商品資料？'))return;state.products.splice(erp90SelectedProduct,1);erp90NewProduct();persist('ERP10.0刪除商品',true);renderSelects();erp90RenderProducts()}
function erp90RenderCustomers(){const q=norm(c90q?.value||'').toLowerCase();const rows=(state.customers||[]).filter(c=>!q||norm([c.code,c.name,c.phone,c.address,c.note].join(' ')).toLowerCase().includes(q));c90count.textContent=`共找到 ${rows.length} 筆客戶資料`;c90list.innerHTML=rows.length?`<table class="erp90-table"><thead><tr><th>編號</th><th>客戶名稱</th><th>電話</th><th>地址</th></tr></thead><tbody>${rows.map(c=>`<tr class="${String(c.id)===String(erp90SelectedCustomer)?'selected':''}" onclick="erp90EditCustomer('${e90(c.id)}')"><td>${e90(c.code)}</td><td><b>${e90(c.name)}</b></td><td>${e90(c.phone)}</td><td>${e90(c.address)}</td></tr>`).join('')}</tbody></table>`:'<div class="erp90-empty">查無客戶資料</div>'}
function erp90EditCustomer(id){const c=(state.customers||[]).find(x=>String(x.id)===String(id));if(!c)return;erp90SelectedCustomer=c.id;c90id.value=c.id;c90title.textContent='修改客戶：'+c.name;c90code.value=c.code||'';c90name.value=c.name||'';c90phone.value=c.phone||'';c90address.value=c.address||'';c90price.value=c.priceType||'suggested';c90discount.value=c.discountFormula||'1';c90note.value=c.note||'';erp90RenderCustomers()}
function erp90NewCustomer(){erp90SelectedCustomer=null;c90id.value='';c90title.textContent='新增客戶';c90code.value=nextFourDigitCode(state.customers||[]);c90name.value=c90phone.value=c90address.value=c90note.value='';c90price.value='suggested';c90discount.value='1'}
function erp90SaveCustomer(){if(!c90name.value.trim())return toast('請輸入客戶名稱');let c=(state.customers||[]).find(x=>String(x.id)===String(erp90SelectedCustomer));if(!c){c={id:Date.now()};state.customers.push(c);erp90SelectedCustomer=c.id}Object.assign(c,{code:c90code.value.trim()||nextFourDigitCode(state.customers),name:c90name.value.trim(),phone:c90phone.value.trim(),address:c90address.value.trim(),priceType:c90price.value,discountFormula:c90discount.value.trim()||'1',note:c90note.value.trim()});persist('ERP10.0修改客戶',true);renderSelects();erp90RenderCustomers();toast('客戶資料已儲存')}
function erp90DeleteCustomer(){if(erp90SelectedCustomer==null)return toast('請先選擇客戶');const c=state.customers.find(x=>String(x.id)===String(erp90SelectedCustomer));if(c?.code==='0001')return toast('一般客戶不能刪除');if(!confirm('確定刪除這筆客戶資料？'))return;state.customers=state.customers.filter(x=>String(x.id)!==String(erp90SelectedCustomer));erp90NewCustomer();persist('ERP10.0刪除客戶',true);renderSelects();erp90RenderCustomers()}
function erp90RenderSuppliers(){const q=norm(s90q?.value||'').toLowerCase();const rows=(state.suppliers||[]).filter(v=>!q||norm([v.code,v.name,v.contact,v.phone,v.address,v.note].join(' ')).toLowerCase().includes(q));s90count.textContent=`共找到 ${rows.length} 筆廠商資料`;s90list.innerHTML=rows.length?`<table class="erp90-table"><thead><tr><th>編號</th><th>廠商名稱</th><th>聯絡人</th><th>電話</th></tr></thead><tbody>${rows.map(v=>`<tr class="${String(v.id)===String(erp90SelectedSupplier)?'selected':''}" onclick="erp90EditSupplier('${e90(v.id)}')"><td>${e90(v.code)}</td><td><b>${e90(v.name)}</b></td><td>${e90(v.contact)}</td><td>${e90(v.phone)}</td></tr>`).join('')}</tbody></table>`:'<div class="erp90-empty">查無廠商資料</div>'}
function erp90EditSupplier(id){const v=(state.suppliers||[]).find(x=>String(x.id)===String(id));if(!v)return;erp90SelectedSupplier=v.id;s90id.value=v.id;s90title.textContent='修改廠商：'+v.name;s90code.value=v.code||'';s90name.value=v.name||'';s90contact.value=v.contact||'';s90phone.value=v.phone||'';s90address.value=v.address||'';s90note.value=v.note||'';erp90RenderSuppliers()}
function erp90NewSupplier(){erp90SelectedSupplier=null;s90id.value='';s90title.textContent='新增廠商';s90code.value=nextFourDigitCode(state.suppliers||[]);s90name.value=s90contact.value=s90phone.value=s90address.value=s90note.value=''}
function erp90SaveSupplier(){if(!s90name.value.trim())return toast('請輸入廠商名稱');let v=(state.suppliers||[]).find(x=>String(x.id)===String(erp90SelectedSupplier));if(!v){v={id:Date.now()};state.suppliers.push(v);erp90SelectedSupplier=v.id}Object.assign(v,{code:s90code.value.trim()||nextFourDigitCode(state.suppliers),name:s90name.value.trim(),contact:s90contact.value.trim(),phone:s90phone.value.trim(),address:s90address.value.trim(),note:s90note.value.trim()});persist('ERP10.0修改廠商',true);renderSelects();erp90RenderSuppliers();toast('廠商資料已儲存')}
function erp90DeleteSupplier(){if(erp90SelectedSupplier==null)return toast('請先選擇廠商');if(!confirm('確定刪除這筆廠商資料？'))return;state.suppliers=state.suppliers.filter(x=>String(x.id)!==String(erp90SelectedSupplier));erp90NewSupplier();persist('ERP10.0刪除廠商',true);renderSelects();erp90RenderSuppliers()}
const erp90OldShowPanel=showPanel;showPanel=function(id){erp90OldShowPanel(id);if(id==='productLookup90'){erp90RenderProducts();if(erp90SelectedProduct<0)erp90NewProduct()}if(id==='customerLookup90'){erp90RenderCustomers();if(erp90SelectedCustomer==null)erp90NewCustomer()}if(id==='supplierLookup90'){erp90RenderSuppliers();if(erp90SelectedSupplier==null)erp90NewSupplier()}};
document.addEventListener('keydown',e=>{const active=document.querySelector('.panel:not(.hidden)')?.id;if(!['productLookup90','customerLookup90','supplierLookup90'].includes(active))return;if(e.key==='F2'){e.preventDefault();active==='productLookup90'?erp90NewProduct():active==='customerLookup90'?erp90NewCustomer():erp90NewSupplier()}if(e.key==='F5'){e.preventDefault();active==='productLookup90'?erp90RenderProducts():active==='customerLookup90'?erp90RenderCustomers():erp90RenderSuppliers()}if(e.key==='Escape')showPanel('dashboard')});
